---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.15.2

inputs:
  - name: dp-search-builder

outputs:
  - name: build

run:
  path: dp-search-builder/ci/scripts/build.sh
